---
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
matrix:
  include:
  - python: 3.6
    env: TOXENV=sphinx
  - python: 3.6
    env: TOXENV=black
  - python: 3.6
    env: TOXENV=pylama
install:
  - pip install tox tox-travis
script:
  - tox
